#define GATT_ATTR_CHAR_MAX_LEN 512

typedef enum {
    IDX_SVC_SCHEDULE,

    IDX_CHAR_PORTIONS,
    IDX_CHAR_PORTIONS_VAL,

    IDX_CHAR_MEASUREMENT,
    IDX_CHAR_MEASUREMENT_VAL,
    IDX_CHAR_MEASUREMENT_CFG,

    IDX_CHAR_EVENTS,
    IDX_CHAR_EVENTS_VAL,


    NUM_ATTR
} gatt_attr_t;